version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=password
    restart: unless-stopped
    networks:
      - lab-network

  # Optional: Add more vulnerable applications
  webgoat:
    image: webgoat/goatandwolf
    container_name: webgoat
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - lab-network
    profiles:
      - extended

networks:
  lab-network:
    driver: bridge

# Usage:
# Basic setup (DVWA only): docker-compose up -d dvwa
# Extended setup: docker-compose --profile extended up -d

